### ISSUE TITLE
Client Crash When Accessing WizardEx Tab from Inventory (Custom Mod List), MC v1.20.1, Fabric v0.92.1, WizardEx:DC v1.1.0

### ISSUE THREAD

**Issue by rxay579** [PlayerEXDirectorsCut/WizardEx#1]
On a custom mod list, when accessing the magic tab from the player screen, the client immediately crashes.
This didn't used to be an issue, but we had updated some of the mods in the mod list since initially starting and are now experiencing the crash issue.
This happens in single player and on a local server, but only the client seems affected.
Latest log and crashlog from single player attached.
Mod list appears to be in the lastest.log.
[latest.log](https://github.com/PlayerEXDirectorsCut/WizardEx/files/15087682/latest.log)
[crash-2024-04-23_22.54.47-client.txt](https://github.com/PlayerEXDirectorsCut/WizardEx/files/15087687/crash-2024-04-23_22.54.47-client.txt)
Hope that is enough to be useful.

*edit*
Did a little digging around and it could be related to changes in Spell Engine, as their changelog mentions breaking changes.
https://modrinth.com/mod/spell-engine/changelog
Could be why the PlayerEx "Ranged Damage" stat hasn't been displaying correctly since a recent update (another issue I've been trying to track down).

*edit*
MC v1.20.1, Fabric v0.92.1, WizardEx:DC v1.1.0

**Comment by rxay579** [comment]
Did some testing in single player and rolled back all mods* related to the Spell Engine / Spell Power Attributes changes.
With those rolled back, accessing the magic tab does not crash the client.

* Pre-API change mod versions:
Archers (RPG Series) v1.1.0
Paladins & Priests (RPG Series) v1.1.3
Wizards (RPG Series) v1.1.1
Jewelry (RPG Series) v1.2.4
Spell Engine v0.13.3
Spell Power Attributes v0.9.19
Simply Swords v1.54.0
Botania Combat v2.0.0

**Comment by karuzumi** [comment]
Hello! The issue is acknowledged and I am working on a fix.

**Comment by karuzumi** [comment]
Hello! This problem **should** be resolved in the new version. Please send another issue if there is another problem! You can download from release, modrinth, or curseforge.
